version: '2.1'

services:

  postgresql:
    container_name: postgresql
    image: sameersbn/postgresql
    restart: always
    environment:
      - PG_PASSWORD=postgrepass
      - DB_NAME=news
      - DB_USER=
      - DB_PASS=
    volumes:
      - /mnt/qnap/docker/data/postgresql:/var/lib/postgresql
      - /mnt/qnap/docker/backups/postgresql:/backup
    ports:
      - 5432:5432

  nginx:
    container_name: nginx
    image: sameersbn/nginx:1.10.2-2
    restart: always
    ports:
      - 80:80
    volumes:
      - /nginx/nginx.conf:/etc/nginx/nginx.conf
      - /nginx/sites-enabled:/etc/nginx/sites-enabled
      - /nginx/www:/www

  cowl-go-services:
    container_name: quzx-services
    image: demas1251/quzx-services
    restart: always
    links:
      - "postgresql:postgresql"
    environment:
      - TWICONKEY=
      - TWICONSEC=
      - TWIACCTOK=
      - TWIACCTOKSEC=
      - USER=
      - PASS=
      - SECRER=secret
      - PORT=
      - DBHOST=postgresql
      - DBPORT=5432
      - DBUSER=
      - DBPASS=
      - DBNAME=news
    ports:
      - 4000:4000
